### ISSUE TITLE
Touchpad Erratic/Stuttering Movement

### ISSUE THREAD

**Issue by MilanParikh** [jc-bao/surface-laptop3-ventura#1]
Hi I have a SL3 13" with the i5, so my EFI is very similar to yours. I am also using the latest BigSurface kext and while my keyboard and touchscreen work fine, I'm noticing the touchpad does not work very well. There is stuttering or lag while moving the cursor. An external mouse works completely smoothly though so I don't think it is a graphics issue. I was wondering if you have the same issue? Or if you know of a fix for this problem? Thanks!

**Comment by jc-bao** [comment]
I'm experiencing the exact same issue! It's really strange because both the external mouse and the touch screen work well, but the mouse occasionally skips. This really disrupts the macOS trackpad experience. I think this might be related to the Big Surface kernel. Here are two related issues:

[Issue 112](https://github.com/Xiashangning/BigSurface/issues/112)
[Issue 79](https://github.com/Xiashangning/BigSurface/issues/79)

**Comment by MohamedRefaat8816** [comment]
Hello I have The same device but with Core i7 when I use your EFI my laptop continue restart can you help me please

**Comment by jc-bao** [comment]
You can seek help on the Hackintosh subreddit. Also, please attach the log file.

One common issue could be an incorrect BIOS setup. Have you disabled Secure Boot?

**Comment by xixi160323** [comment]
> Hello I have The same device but with Core i7 when I use your EFI my laptop continue restart can you help me please
I also have the same configuration and have encountered frequent restart issues

**Comment by xixi160323** [comment]
> 您好，我有相同的设备，但是当我使用您的EFI时，使用Core i7，我的笔记本电脑继续重启，您能帮我吗
As of now, I seem to have solved the problem with the reboot, which is a kernel panic due to the graphics card.
It may be different on the same 1035G7, like my 1035G7 buffer ID needs to be customized, I tried almost everything possible in the ID list. In the end 0x8A5C0001 the reboot problem was successfully solved, and some buffer frame memory settings were also required:
framebuffer-stolenmem=000000C0
framebuffer-stolenmem=0000B003
That's all I can provide so far, I hope to help you solve the problem, and I wish you a speedy success!

**Comment by xixi160323** [comment]
> 您好，我有相同的设备，但是当我使用您的EFI时，使用Core i7，我的笔记本电脑继续重启，您能帮我吗
截止目前，我似乎解决了重启的问题，重启问题是由于显卡导致的内核崩溃。
在同样的1035G7上可能有所不同，比如我的1035G7缓冲帧ID需要定制，我几乎尝试了ID列表中的所有可能。最终0x8A5C0001成功的解决了重启的问题，此外还需要一些缓冲帧内存的设置：
AAPL,ig-platform-id=01005C8A 
framebuffer-unifiedmem=000000C0
framebuffer-stolenmem=0000B003
<img width="653" alt="截屏2024-06-14 19 22 19" src="https://github.com/jc-bao/surface-laptop3-ventura/assets/156495956/ceaaa14e-3499-4d4a-adf5-c8c543b79448">
<img width="662" alt="截屏2024-06-14 19 24 39" src="https://github.com/jc-bao/surface-laptop3-ventura/assets/156495956/fca3428b-8e31-4a9d-aa57-c703fc9ac90b">

目前我所能提供的信息就是这些，这耗费了我大量的时间，我不想你也一样。
希望能帮助你解决问题，祝早日成功！

**Comment by jc-bao** [comment]
你好，很遗憾你碰到了这么多问题。我的旧i5屏幕裂了，新买的i7 surface laptop 3工作正常，安装很顺利。因为我不是这方面的专家，恐怕无法提供更多帮助了。 😢

**Comment by jlempen** [comment]
Hey @jc-bao,

**I found the solution for a buttery-smooth trackpad without lagging/skipping** on my Surface Laptop 3 15" i7. This should work for the Surface Book 3 as well.

You have to downgrade your UEFI firmware to the last known working version `13.101.140.0` for both the SL3 and SB3 and downgrade the `BigSurface.kext` to [version 6.2](https://github.com/Xiashangning/BigSurface/releases/download/v6.2/BigSurface.zip).

This UEFI firmware is included in the March 01 2022 release update package for the SL3 (SurfaceLaptop3_Win10_19041_22.011.9779.0.msi) and the May 24 2022 release update package for the SB3 (SurfaceBook3_Win10_19041_22.034.40281.0.msi). As of today, both update packages are not available on Micro$oft's support site anymore, but you'll find them on the [Softpedia website](https://drivers.softpedia.com).

Follow the very clear instructions on the [surface-uefi-firmware Github](https://github.com/linux-surface/surface-uefi-firmware) to downgrade the UEFI firmware. 

In a nutshell:
1. Boot with a Linux Live ISO, preferably a Debian, Arch or Fedora based distribution, as you'll have to install the three packages `msiextract`, `gcab` and `dos2unix` for the downgrade script to work.
2. Download the script from the [surface-uefi-firmware Github](https://github.com/linux-surface/surface-uefi-firmware) and add `OnlyTrusted=false` in `/etc/fwupd/daemon.conf`. 
3. Run the `repack.sh` script, which will unpack the MSI update package, extract all UEFI firmwares from it and generate fwupd metadata for it. Once the script finishes you'll find a list of cab files inside the `fwupdates` folder. 
4. Using `fwupd`, install all the firmware files at once.

This will reboot the laptop and downgrade all UEFI firmwares at once, which takes around 10 minutes. You'll see progress bars with different colours depending on which type of firmware is being flashed.
Once the process is done, your laptop will restart a few times and seem to hang on the Surface logo for 20 or 30 seconds each time, this is normal. Then it will restart for good to your OpenCore picker.
Now restart while holding the F4/Volume Up key to check the firmware version in the UEFI. In the Firmware section, `System UEFI` should now show `13.101.140`.

Reboot into macOS. The keyboard and trackpad should be working, but the trackpad will still lag/skip as before. To fix that, download [BigSurface version 6.2](https://github.com/Xiashangning/BigSurface/releases/download/v6.2/BigSurface.zip) and replace your current `BigSurface.kext`. Do do so, **delete** your current `BigSurface.kext` in the OC kext folder and in your `config.plist` and add v6.2 in the specified order:

<img width="932" alt="BigSurface v6.2 kext order" src="https://github.com/Xiashangning/BigSurface/assets/37862766/c7762c72-bf3a-419f-9e26-8a118256c1ad">

Reboot and you're done. Enjoy a perfect trackpad on your Surface Hackintosh!

A couple of caveats:

- If you are using Windows on the laptop, you'll have to find a way to prevent Windows Update from updating the firmware to the latest version again! I don't know how to do that, but DuckDuckGo is your friend.
- If you are using Xiashangning's [IPTS daemon](https://github.com/Xiashangning/IPTSDaemon) to enable the touchscreen, you'll probably have to downgrade that as well to an [older version](https://github.com/Xiashangning/IPTSDaemon-old). This shouldn't be an issue for Surface Laptop 3 owners (who needs a touchscreen on a non-foldable, non 2-in-1 style laptop), but it could be problematic for Surface Book 3 users.
