### ISSUE TITLE
The exact same configuration often encounters restarts during startup.

### ISSUE THREAD

**Issue by xixi160323** [jc-bao/surface-laptop3-ventura#2]
Hello, I'm very lucky to see that your configuration is exactly the same as mine.
My computer uses win10 and macos 13.6 dual system.
However, when entering the OS, it is often encountered that the system needs to be restarted.
The code is attached in the picture -
Do you use a single system? I have not turned on the safe mode. Only when it is turned off can I enter the oc to select the dual system switch.
Is there a problem with the BIOS settings? Could you share your BIOS settings.
We look forward to your reply. Thank you!
![1 jpg](https://github.com/jc-bao/surface-laptop3-ventura/assets/156495956/92f426f6-19de-4315-abda-b6b69932a360)

**Comment by jc-bao** [comment]
That's weird, and I haven't experienced anything similar. For the BIOS, the only thing I do is disable the secure boot. It seems like an Intel Bluetooth issue. Maybe disabling itlwm would work. Can you also confirm that you are using the correct itlwm version for your OS? Anyway, I would suggest posting an issue on itlwm to see if anybody has encountered the same issue.

**Comment by xixi160323** [comment]
Thank you for your reply
At present, it seems that it may be a Bluetooth issue
Will this line of code not appear in your startup code?
Also, I replaced the hard drive,
What is the model of your hard drive? Would it be convenient to provide it?
Thank you very much for your help!

**Comment by xixi160323** [comment]
Additionally, you mentioned in the article that fixing Bluetooth 4.0.

What did it do and did it make any modifications to the ket file?

I didn't understand

**Comment by jc-bao** [comment]
The drive I used was builtin. 
For bluetooth, I didn't change any kext.

**Comment by xixi160323** [comment]
As of now, I seem to have solved the problem with the reboot, which is a kernel panic due to the graphics card.
It may be different on the same 1035G7, like my 1035G7 buffer ID needs to be customized, I tried almost everything possible in the ID list. In the end 0x8A5C0001 the reboot problem was successfully solved, and some buffer frame memory settings were also required:
<img width="653" alt="截屏2024-06-14 19 22 19" src="https://github.com/jc-bao/surface-laptop3-ventura/assets/156495956/7e99dd82-fe00-4f57-86d0-09406622e2ed">
<img width="662" alt="截屏2024-06-14 19 24 39" src="https://github.com/jc-bao/surface-laptop3-ventura/assets/156495956/7c74714b-5852-4135-863c-9614e2d52079">

**Comment by jc-bao** [comment]
I don't think it is related to the cpu model cuz my new i7 sl3 works very well with exact same config. 

Could it be related to surface hardware? Like the ssd or something goes wrong.
